require: rubocop-rspec

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 128

# we don't support ruby 1.8 any more
Style/HashSyntax:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Rails:
  Enabled: true
