business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 6:00 pm
  holidays:
    - Sep 05, 2016
    - Nov 24, 2016
    - Nov 25, 2016
    - Dec 23, 2016
    - Dec 26, 2016
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
