require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ParentOrgsController, type: :controller do

  let!(:parent_org) { FactoryGirl.create(:parent_org) }
  let!(:user) { FactoryGirl.create(:user, :role_names => ["Admin"]) }

  let(:valid_attributes) {
    {
      name: "Parent Org",
      code: "POCODE"
    }
  }

  let(:invalid_attributes) {
    {
      name: nil,
      code: "something"
    }
  }

  before :each do
    login_as user
  end

  describe "GET #index" do
    it "assigns all parent_orgs as @parent_orgs" do
      should_authorize(:index, ParentOrg)
      get :index
      expect(assigns(:parent_orgs)).to include(parent_org)
    end
  end

  describe "GET #show" do
    it "assigns the requested parent_org as @parent_org" do
      should_authorize(:show, parent_org)
      get :show, {:id => parent_org.id}
      expect(assigns(:parent_org)).to eq(parent_org)
    end
  end

  describe "GET #new" do
    it "assigns a new parent_org as @parent_org" do
      should_authorize(:new, ParentOrg)
      get :new
      expect(assigns(:parent_org)).to be_a_new(ParentOrg)
    end
  end

  describe "GET #edit" do
    it "assigns the requested parent_org as @parent_org" do
      should_authorize(:edit, parent_org)
      get :edit, {:id => parent_org.id}
      expect(assigns(:parent_org)).to eq(parent_org)
    end
  end

  describe "POST #create" do
    before :each do
      should_authorize(:create, ParentOrg)
    end

    context "with valid params" do
      it "creates a new ParentOrg" do
        expect {
          post :create, {:parent_org => valid_attributes}
        }.to change(ParentOrg, :count).by(1)
      end

      it "assigns a newly created parent_org as @parent_org" do
        post :create, {:parent_org => valid_attributes}
        expect(assigns(:parent_org)).to be_a(ParentOrg)
        expect(assigns(:parent_org)).to be_persisted
      end

      it "redirects to the created parent_org" do
        post :create, {:parent_org => valid_attributes}
        expect(response).to redirect_to(ParentOrg.find_by(:name => "Parent Org"))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved parent_org as @parent_org" do
        post :create, {:parent_org => invalid_attributes}
        expect(assigns(:parent_org)).to be_a_new(ParentOrg)
      end

      it "re-renders the 'new' template" do
        post :create, {:parent_org => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    before :each do
      should_authorize(:update, parent_org)
    end

    context "with valid params" do
      let(:new_attributes) {
        {
          name: "New Name",
          code: "NUCODE"
        }
      }

      it "updates the requested parent_org" do
        put :update, {:id => parent_org.id, :parent_org => new_attributes}
        parent_org.reload
        expect(parent_org.name).to eq("New Name")
      end

      it "assigns the requested parent_org as @parent_org" do
        put :update, {:id => parent_org.id, :parent_org => valid_attributes}
        expect(assigns(:parent_org)).to eq(parent_org)
      end

      it "redirects to the parent_org" do
        put :update, {:id => parent_org.id, :parent_org => valid_attributes}
        expect(response).to redirect_to(parent_org)
      end
    end

    context "with invalid params" do
      it "assigns the parent_org as @parent_org" do
        put :update, {:id => parent_org.id, :parent_org => invalid_attributes}
        expect(assigns(:parent_org)).to eq(parent_org)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => parent_org.id, :parent_org => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before :each do
      should_authorize(:destroy, parent_org)
    end

    it "destroys the requested parent_org" do
      expect {
        delete :destroy, {:id => parent_org.id}
      }.to change(ParentOrg, :count).by(-1)
    end

    it "redirects to the parent_orgs list" do
      delete :destroy, {:id => parent_org.id}
      expect(response).to redirect_to(parent_orgs_url)
    end
  end

end
